location_Delhi = {
    'Connaught Place': 1,
    'Aurungzeb Road': 2,
    'Greater Kailash': 3,
    'Defence Colony': 4,
    'Vasant Vihar': 5,
    'Hauz Khas': 6,
    'Green Park': 7,
    'Anand Niketan': 8,
    'Panchsheel Park': 9,
    'New Friends Colony': 10,
    'Siri Fort': 11,
    'Malviya Nagar': 12,
    'East of Kailash': 13,
    'Karol Bagh': 14,
    'Janakpuri': 15,
    'Chattarpur': 16,
    'Punjabi Bagh': 17,
    'Shahdara': 18,
    'Dwarka Sector 21': 19,
    'Sector 12 Dwarka': 20,
    'Mayur Vihar': 21,
    'Sector 19B': 22,
    'Block H': 23,
    'Sainik Farms': 24,
    'Model Town': 25,
    'Jasola': 26,
    'Moti Nagar': 27,
    'Lajpat Nagar': 28,
    'Badarpur': 29,
    'R.K. Puram': 30,
    'Kalkaji': 31,
    'Sector 14 Rohini': 32,
    'Lalita Park': 33,
    'Malka Ganj': 34,
    'Block F': 35,
    'Sector 6 Rohini': 36,
    'West End': 37,
    'Sector 10': 39,
    'Shanti Park Dwarka': 40,
    'Sidhartha Nagar': 41,
    'Dharampura': 42,
    'Civil Lines': 43,
    'Nirman Vihar': 44,
    'Block A': 45,
    'Sarita Vihar': 46,
    'Geetanjali Enclave': 47,
    'Dhaka Village': 48,
    'Vasundhara Enclave': 49,
    'Dwarka 11 Sector': 50,
    'Sector 11 Dwarka': 51,
    'Sector 19 Dwarka': 52,
    'Mansarovar Garden': 53,
    'Block D': 54,
    'Pushpanjali Enclave': 55,
    'New Ashok Nagar': 56,
    'Kalkaji Extension': 57,
    'Sector-14 Rohini': 58,
    'Govindpuri': 59,
    'Jor Bagh': 60,
    'Paryavaran Complex': 61,
    'IP Extension': 62,
    'Azadpur': 63,
    'Sultanpur': 64,
    'Zakir Nagar': 65,
}






location_Mumbai = {
    'Malabar Hill': 1,
    'Bandra West': 2,
    'Juhu': 3,
    'South Mumbai': 4,
    'Worli': 5,
    'Hiranandani Estates': 6,
    'Powai': 7,
    'Andheri West': 8,
    'Santacruz West': 9,
    'Vile Parle West': 10,
    'Khar': 11,
    'Parel': 12,
    'Dadar West': 13,
    'Bandra Kurla Complex': 14,
    'Versova': 15,
    'Lower Parel': 16,
    'Kandivali West': 17,
    'Goregaon West': 18,
    'Khar East': 19,
    'Ghatkopar West': 20,
    'Mulund': 21,
    'Chembur': 22,
    'Dadar East': 23,
    'Goregaon (East)': 24,
    'Sector 5 Ulwe': 25,
    'Navi Mumbai': 26,
    'Thane': 27,
    'Shirgaon': 28,
    'Dahisar': 29,
    'Bhayandarpada': 30,
    'Virar East': 31,
    'Jogeshwari West': 32,
    'Matunga': 33,
    'Ghatkopar East': 34,
    'Kalyan West': 35,
    'Goregaon East': 36,
    'Malad West': 37,
    'Santacruz East': 38,
    'Mahalaxmi': 39,
    'Chedda Nagar': 40,
    'Sector 21 Kamothe': 41,
    'Kalyan': 42,
    'Sector 35 D Kharghar': 43,
    'Virar West': 44,
    'Ambarnath': 45,
    'Gandhar Nagar': 46,
    'Shastri Nagar': 47,
    'Kandivali East': 48,
    'Mira Road': 49,
    'Akurli Nagar': 50,
    'Badlapur': 51,
    'Chembur Shell Colony': 52,
    'Kopar Khairane': 53,
    'Navi Basti': 54,
    'Sector 12 A': 55,
    'Jogeshwari East': 56,
    'Patlipada': 57,
    'Hadapsar': 58,
    'Sion': 59,
    'Ghatkopar': 60,
    'Kandivali (W)': 61,
    'Kopra': 62,
    'Sector 8 Sanpada': 63,
    'Tardeo': 64,
    'Dhakoli': 65,
    'Dombivali East': 66,
    'Bhayandar East': 67,
    'Dharavi': 68,
    'Ulwe': 69,
    'Majiwada': 70,
    'Badlapur East': 71,
    'Thakur Village': 72,
    'Vikhroli': 73,
    'Pali Hill': 74,
    'Mira Bhayandar': 75,
    'Shiv Sagar Estate': 76,
    'Taloja': 77,
    'Ghansoli': 78,
    'Sector 12 Kharghar': 79,
    'Kalwa': 80,
    'Nalasopara West': 81,
    'Bandra East': 82,
    'Sewri': 83,
    'Dronagiri': 84,
    'Goregaon (West)': 85,
    'Four Bungalows': 86,
    'Haji Ali': 87,
    'Vasai West': 88,
    'Taloje': 89,
    'Rahul Kanchan': 91,
    'Kalyan East': 92,
    'Sahakar Nagar': 93,
    'Sector 19 Kamothe': 94,
    'Virar': 95,
    'Kolshet Road': 96,
    'Dahisar West': 97,
    'Palm Beach': 98,
    'Gulal Wadi': 99,
    'Karjat': 100,
    'Western Express Highway Kandivali East': 101,
    'Nallasopara East': 102,
    'Mumbaî': 103,
    'Rustomjee Global City': 104,
}


location_Bangalore = {
    'Indira Nagar': 1,
    'Koramangala': 2,
    'Sadashiva Nagar': 3,
    'Malleswaram': 4,
    'Jayanagar': 5,
    'Whitefield': 6,
    'HBR Layout': 7,
    'RT Nagar': 8,
    'JP Nagar': 9,
    'BTM Layout': 10,
    'Bellandur': 11,
    'Brookefield': 12,
    'Sarjapur': 13,
    'Hennur': 14,
    'Gottigere': 15,
    'Electronic City': 16,
    'Basavanagudi': 17,
    'Hebbal': 18,
    'Hoskote': 19,
    'Yelahanka': 20,
    'Kengeri': 21,
    'Nandini Layout': 22,
    'Frazer Town': 23,
    'Rajajinagar': 24,
    'Anekal City': 25,
    'Dasarahalli': 26,
    'Doddanekundi': 27,
    'Hosur Main Road': 28,
    'Mallesandra': 29,
    'Pattanagere': 30,
}


location_Kolkata = {
    'Alipore': 1,
    'Bhawanipur': 2,
    'Ballygunge': 3,
    'Gariahat': 4,
    'Salt Lake City': 5,
    'New Town': 6,
    'Rajarhat': 7,
    'Jadavpur': 8,
    'Golf Green': 9,
    'Lake Gardens': 10,
    'Narendrapur': 11,
    'Kalighat': 12,
    'Howrah': 13,
    'Park Circus': 14,
    'Shyamnagar': 15,
    'Hazra': 16,
    'Tollygunge': 17,
    'Baranagar': 18,
    'Madhyamgram': 19,
    'Sector IV Salt Lake': 20,
    'New Alipore': 21,
    'Bansdroni': 22,
    'Behala': 23,
    'Kamalgachhi': 24,
    'Behala Chowrasta': 25,
    'Dakshineswar': 26,
    'Rajpur': 27,
    'Baghajatin': 28,
    'Barrackpore': 29,
    'Dum Dum Cantonment': 30,
    'Dum Dum': 31,
    'Rishra': 32,
    'Beliaghata': 33,
    'Kamardanga': 34,
    'Uttarpara Kotrung': 35,
    'Birati': 36,
    'Durgapur': 37,
    'Selimpur': 38,
    'Taltala': 39,
    'Elgin': 40,
    'Bansdroni Metro Station Road': 41,
    'Patuli': 42,
    'Bhowanipore': 43,
    'Chandannagar': 44,
    'Durganagar': 45,
    'New Town Action Area I': 46,
    'Liluah': 47,
    'New Barrackpur': 48,
    'Purbalok': 49,
    'N S C Bose Road': 50,
    'Shibpur': 51,
    'Jatragachi Flyover': 52,
    'Bankra': 53,
    'Mankundu': 54,
    'Haltu': 55,
    'Paschim Barisha': 56,
    'Selimpur Road': 57,
    'Fartabad': 58,
    'Surjaysen Nagar': 59,
    'Kamal Bagan': 60,
    'Lohar Bridge': 61,
    'Ariadaha': 62,
    'Puttenahalli': 63,
    'Bangur Avenue': 64,
    'Mominpore': 65,
    'Panchpota': 66,
    'Kestopur': 67,
    'Garia Rathtala': 68,
    'Noapara': 69,
    'Kharda': 70,
    'Colony Park': 71,
    'Aakash Ganga': 72,
    'Action Area III': 73,
    'Kudghat Bridge': 74,
    'New Shakuntala Park': 75,
    'Kasba Siemens': 76,
    'Kudgat': 77,
    'Royal Park': 78,
    'Timberwood': 79,
    'Barisha Purba Para Road': 80,
    'Civil Township': 81,
    'Nayabad': 82,
    'Gitanjali Metro Station Road': 83,
    'Budge Budge': 84,
    'Konnagar': 85,
    'Tangra': 86,
    'Nalhati': 87,
    'Kolkata': 88,
    'Mohisbathan': 89,
    'Chkravarti Para': 90,
    'Buroshibtalla': 91,
    'Maheshtala': 92,
    'Sodepur': 93,
    'Tiljala': 94,
    'Raja Ram Mohan Roy Road': 95,
    'Dum Dum Metro': 96,
    'Nandi Bagan': 97,
    'Action Area II Newtown': 98,
    'Kamalgachhi More': 99,
    'Roy Bahadur Road': 100,
    'Sarat Bose Road': 101,
    'Howrah Railway Station': 102,
    'Kamarhati on BT Road': 103,
    'Regent Park': 104,
    'Eastend Park Kalikapur': 105,
    'Rabindra Sarovar': 106,
    'Natun Para': 108,
    'Garfa': 109,
    'Biral': 110,
    'Naktala': 111,
    'Bijoygarh': 112,
    'Joka': 113,
    'Mali Panchghara': 115,
    'Krishna': 116,
    'Chandmari': 117,
    'Phool Bagan': 118,
    'New Alipore Road': 119,
    'Kamalgazi Flyover': 120,
    'Sinthi': 121,
    'Selimpur Lane': 122,
    'Dhapa': 123,
    'Mahamayatala': 124,
    'Prafulla Kanan': 125,
    'Uttar Panchanna Gram': 126,
    'Jadhavpur': 127,
    'Dum Dum Park': 128,
    'Tagore Park': 129,
    'VIP Nagar': 130,
    'Sapuipara': 131,
    'Joginder Garden Lane': 132,
    'Baidyabati': 133,
    'Netaji Nagar': 136,
    'Sodepur Road': 137,
    'Southern Avenue': 138,
    'Kalitala Road': 139,
    'Tibetan School': 142,
    'Mohammad Farm': 143,
    'Haldirams': 144,
    'Block O': 145,
    'Airport Area': 146,
    'Bakhra Nagar': 147,
    'Sonarpur': 148,
    'Lohar': 150,
    'Bonhooghly on BT Road': 151,
    'Belia Matri': 152,
    'Jodthbhim Newtown': 153,
    'Harinavi': 154,
    'Bhanga': 155,
    'Draupadi Nagar': 156,
    'Jorabagan': 157,
    'Premanand Nagar': 159,
    'VIP Road': 160,
    'Khasmallik': 162,
    'Hinjewadi': 163,
    'Bomikhal': 164,
    'Sidhant School': 165,
    'Uttarpara': 166,
    'Shahnawaz': 167,
    'Birnagar': 168,
    'Sahapur': 169,
    'Sector II Salt Lake': 171,
    'Salt Lake': 173,
    'Kadamtala': 174,
    'Kazipara': 175,
    'Raghu Sharan': 176,
    'University College': 177,
    'Sirajganj': 178,
    'Dhanbat': 179,
    'Ghosh Para': 180,
    'Rajarhat Chowmatha': 182,
    'Barisha': 183,
    'Burmese Temple': 185,
    'Pratapaditya Road': 186,
    'Baruipur': 187,
    'Action Area IIB Newtown': 188,
    'Commercial Market': 189,
    'Aminabad': 190,
    'Maharaja Keshav Chandra': 191,
    'Ghosh Bagan': 192,
    'Khalapur': 194,
    'Jatragachi': 195,
    'Reekjoyoni': 197,
    'North Dumdum': 198,
    'South Dumdum': 199,
    'Chingrighata': 200,
    'Ramlal Bazaar': 201,
    'Nagerbazar': 203,
    'Katwaria Sarai': 204,
    'Brahmapur Road': 205,
    'Kalikapur': 206,
    'Bharat Nagar': 207,
    'Kalighat Metro': 208,
    'Garia Place': 209,
}


location_Chennai = {
    'Mylapore': 1,
    'Adyar': 2,
    'Anna Nagar': 3,
    'Besant Nagar': 4,
    'T Nagar': 5,
    'Royapettah': 6,
    'Nungambakkam': 7,
    'Velachery': 8,
    'Ashok Nagar': 9,
    'Teynampet': 10,
    'Guindy': 11,
    'Ambattur': 12,
    'Pallikaranai': 13,
    'Thiruvanmiyur': 14,
    'Purasawalkam': 15,
    'Vadapalani': 16,
    'Kilpauk': 17,
    'Chennai City Center': 18,
    'Chromepet': 19,
    'Alwarpet': 20,
    'Chetpet': 21,
    'Shenoy Nagar': 22,
    'Porur': 23,
    'West Mambalam': 24,
    'Kotturpuram': 25,
    'Purasaiwakkam': 26,
    'Thoraipakkam': 27,
    'Pallavaram': 28,
    'Perungudi': 29,
    'Tamaram East': 30,
    'Navallur': 31,
    'Alandur': 32,
    'Mandaveli': 33,
    'Kottivakkam': 34,
    'Nandanam': 35,
    'Saidapet': 36,
    'Karapakkam': 37,
    'Madipakkam': 38,
    'Ottiambakkam': 39,
    'Egmoe': 40,
    'Ambattur INDUSTRIAL ESTATE': 41,
    'Mogappair East': 43,
    'Thirumudivakkam': 44,
    'Kumananchavadi': 45,
    'Thalambur': 46,
    'Selaiyur': 47,
    'Vengambakkam': 48,
    'Periyapanicheri': 49,
    'Palavakkam': 50,
    'Varnam': 51,
    'Perumbakkam': 52,
    'Kil Ayanambakkam': 53,
    'Thirumazhisai': 54,
    'Moralady': 55,
    'Injambakkam': 56,
    'Irumbuliyur': 57,
    'Kattupakkam': 58,
    'Kundrathur': 59,
    'Gowrivakkam': 60,
    'Madhavaram': 61,
    'Badarinarayanam': 62,
    'Jaya Nagar': 63,
    'Vandalur': 64,
    'Kattankulathur': 65,
    'Singaperumal Koil': 67,
    'Maramma Nagar': 68,
    'Kodambakkam': 69,
    'Maambahalam': 70,
    'Mogappair': 71,
    'Hospital Road': 72,
    'Manapakkam': 73,
    'Kovilambakkam': 74,
    'Gopalapuram': 75,
    'Adambakkam': 76,
    'Vettuvankani': 77,
    'Thiruvottiyur': 78,
    'Vallam': 79,
    'Iyyappanthangal': 80,
    'Ramapuram': 81,
    'Padi': 82,
    'Sithalapakkam': 83,
    'Poonamallee': 84,
    'Thiruneermalai': 85,
    'Egatoor': 86,
    'Choolaimedu': 87,
    'East Tambaram': 89,
    'Kottambakkam': 90,
    'Chengalpattu': 91,
    'Thirumullaivoyal': 92,
    'Mudichur': 93,
    'Pudupakkam': 94,
    'Manikandan Nagar': 95,
    'Rajakilpakkam': 96,
    'Kuthambakkam': 97,
    'Mahalakshmi Nagar': 98,
    'Kottapet': 99,
    'Karakudi': 100,
    'Adhanur': 101,
    'Esthathai Colony': 102,
    'Vadavalli': 103,
    'Manali': 104,
    'Balamurugan Nagar': 105,
    'Aminjikarai': 106,
    'Mogapair': 107,
    'Kumarasamy Nagar': 108,
    'Sembakkam': 109,
    'Thayur': 110,
    'Hennur Road': 111,
    'Irandankattalai': 112,
    'Kodumbakkam': 113,
    'Sundar Nagar': 114,
    'Puzhal': 115,
    'Palakkad': 116,
    'Sholinganallur': 117,
    'Chennai Bypass': 118,
    'Ponnamalle': 119,
    'Mapletown': 120,
    'Kettuvankani': 121,
    'Nesapakkam': 123,
    'Urapakkam': 125,
    'Siruseri': 126,
    'Ellaiyamman Koil': 127,
    'Tamaram': 128,
    'Semmancheri': 129,
    'Seethan thevar': 130,
    'Virugambakkam': 131,
    'Mevalurkuppam': 132,
    'Chitlapakkam': 133,
    'Srinivas Nagar': 134,
    'Tondiarpet': 135,
    'Thiruverkadu': 136,
    'Nemmeli': 137,
    'GTT Colony': 138,
    'Vellakkal': 139,
    'Pazavanthangal': 140,
    'Chinese Town': 141,
    'Thambaram East': 142,
    'Brahmin Gully': 143,
    'Sunnambu Kolathur S Kolathur': 144,
    'Medavakkam': 145,
    'Nandambakkam': 146,
    'Valasaravakkam': 147,
    'Ramavaram': 148,
    'Old Mambalam': 150,
    'Tamil Nadu House Building': 152,
    'Kelambakkam': 153,
    'GKM Colony': 154,
    'Kandagai': 155,
    'Kunnathur': 156,
    'New Kottivakkam': 157,
    'Tamilnadu BDO': 158,
    'Akra': 161,
    'Block O': 162,
    'Pettai': 163,
    'Pallarhuttai': 164,
    'Sanganoor': 165,
    'Vadakkupattu': 166,
    'Ekkatuthangal': 167,
    'Kolathur': 168,
    'Kulkali': 169,
}


location_Hyderabad = {
    'Banjara Hills': 1,
    'Jubilee Hills': 2,
    'Hitech City': 3,
    'Gachibowli': 4,
    'Madhapur': 5,
    'Begumpet': 6,
    'Ameerpet': 7,
    'JNTU': 8,
    'Kondapur': 9,
    'KPHB': 10,
    'Himayat Nagar': 11,
    'Madhura Nagar': 12,
    'Tarnaka': 13,
    'Mehdipatnam': 14,
    'Toli Chowki': 16,
    'Tolichowki': 17,
    'Sainikpuri': 18,
    'LB Nagar': 19,
    'Yapral': 20,
    'Kukatpally': 21,
    'Adibatla': 22,
    'Gandipet': 23,
    'Nizampet': 24,
    'Dilsukh Nagar': 25,
    'Uppal': 26,
    'Shamshabad': 27,
    'Saidabad': 28,
    'Moosapet': 29,
    'Shankarpalli': 30,
    'Nagole': 31,
    'Serilingampally': 32,
    'Kondakal': 33,
    'Gopal Nagar': 34,
    'Pragathi Nagar': 35,
    'Medchal': 36,
    'Malakpet': 37,
    'Habsiguda': 38,
    'Chikadapally': 39,
    'Hyderabad': 40,
    'Fernland': 41,
    'Ramachandra Puram': 42,
    'Kapra': 43,
    'Bilal Colony': 44,
    'Rajendra Nagar': 45,
    'Santoshnagar': 46,
    'Bowenpally': 47,
    'Mansoorabad': 48,
    'Manikonda': 49,
    'Gajularamaram': 50,
    'Isnapur': 51,
    'Shenoy Nagar': 52,
    'Malkajgiri': 53,
    'Kismatpur': 54,
    'Visaka Colony': 55,
    'Puppalaguda': 56,
    'Domalguda': 57,
    'Film Nagar': 58,
    'Nallagandla': 59,
    'Khajaguda': 60,
    'Sri Nagar Colony': 61,
    'Balanagar': 62,
    'Padi': 63,
    'Gajulramaram Kukatpally': 64,
    'Venkat Nagar Colony': 65,
    'Barkatpura': 66,
    'Mohammed Nagar': 67,
    'Adda Gutta': 68,
    'New Nallakunta': 69,
    'Chandanagar': 70,
    'Aushapur': 71,
    'Hitech Gardens': 72,
    'Kondapoor': 73,
    'HMT Hills': 74,
    'Kothapet': 75,
    'Parvati Colony': 76,
    'Boduppal': 77,
    'Vanasthalipuram': 78,
    'Pocharam': 79,
    'Dammaiguda': 80,
    'Kompally': 81,
    'Parmesh Nagar': 82,
    'Nacharam': 83,
    'West Marredpally': 84,
    'Mallamarathm Hyderabad': 85,
    'Sikandarabad': 86,
    'Beeramguda': 87,
    'Old Bowenpally': 88,
    'Yellareddyguda': 89,
    'Ottiyambakkam': 90,
    'Zamistanpur': 91,
    'Kistareddypet': 92,
    'Uppal Kalan': 93,
    'Old Nallakunta': 94,
    'Dullapally': 95,
    'Vizag Colony': 96,
    'Vittal Rao Nagar': 97,
    'Sri Ram Nagar': 98,
    'Singhpur': 99,
    'Boiguda': 100,
    'Nallakunta': 101,
    'Chintal Basthi': 102,
    'Chikpo School': 103,
    'Srofalgan': 104,
    'Gopanpally': 105,
    'Narayanguda': 106,
    'D D Colony': 107,
    'Pallikaranai': 108,
    'Karimnagar': 109,
    'Lingampalli': 110,
    'Palia Mown': 111,
    'KP Road': 113,
    'Karwan': 114,
    'Ameerpet Road': 115,
    'Rajbhavan Road Somajiguda': 116,
    'Vijayawada Road': 117,
    'Khizra Enclave': 118,
    'Flat No 102': 119,
    'Gandhi Nagar': 120,
    'KCHC Road': 121,
    'Nakkalapathi': 122,
    'Zamir Rafi': 123,
    'Nagaram': 124,
    'Nacharam Industrial Area': 125,
    'Yanamalu': 126,
    'Srinivasa Colony': 127,
    'Kaseez Colony': 128,
    'Gadwal': 129,
    'Peddanabail': 130,
    'Masjid Narayana': 131,
    'Banjara Hills Road Number 12': 132,
    'Suchitra': 133,
    'Patancheru': 134,
    'Adharsh Nagar': 135,
    'Alwal': 136,
    'Vivekananda Nagar Colony': 137,
    'Secunderabad Railway Station Road': 138,
    'Chittra': 139,
    'Whisper Valley': 140,
}
